# -*- coding: utf-8 -*-
"""cube_Of_First_N_natural_Numbers.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AkLARgl3FJAlKSuZGt40P0bq5VYNFZ79
"""

def findCubeSum(n):
    sum = 0
    for value in range(1, n+1):
        sum += value**3
    return sum

n = int(input("Enter the value of n : "))
print("Cube sum : ", findCubeSum(n))