# -*- coding: utf-8 -*-
"""emoji.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13k32sleVW__y1EhVkmkWT2weJPO2A40x
"""

pip install emojis

pip install emojis

import emojis

emojified = emojis.encode('this is a message with emojis:snake: :smile:')
print(emojified)

print(emojis.encode('Always keep smiling :smile:'))

print(emojis.encode('stay safe in coron and always wear a :mask:'))